### ISSUE TITLE
[Feature] 🎉 新功能预告：现代化 UI 适配、多机多卡集群管理、CPU/内存实例间隔离……

### ISSUE THREAD

**Issue by Harry-zklcdc** [mayooot/gpu-docker-api#18]
> [!NOTE]
> 待整理、完善后开源非关键代码，仅供个人、学术使用。如需体验/测试，可联系 zklcdc@qq.com 获取

## 🌈 特性

- [x] 现代化 UI
- [x] 支持暗黑模式 
- [x] 多机多卡管理
- [x] CPU/内存实例间隔离
- [x] 自由缩放配置
- [x] 自动配置 SSH
- [x] 集成 Jupyter NoteBook
- [x] 集成 Grafana + Prometheus 监控 CPU、内存、GPU/显存使用
- [x] 支持无卡模式
- [ ] 仪表盘
- [ ] 管理员面板
- [ ] 支持版本控制
- [ ] 支持更换镜像
- [ ] 计费功能

### 登录
![QQ_1728576700095](https://github.com/user-attachments/assets/22e484a2-ab42-4bf1-863b-140364a4e22d)

### 注册
![QQ_1728576729844](https://github.com/user-attachments/assets/809c215e-3c73-4d31-9f3e-ff1bec7493db)

### 实例管理
![61619efed9e071a90098e5a896bdb799](https://github.com/user-attachments/assets/b1fd2b1e-6ff8-4d00-b7a0-aa97fb7d8b5c)
![53e446d29f6d18f72f4a37ca3a6083cd](https://github.com/user-attachments/assets/67ec1741-0d99-46ed-98aa-7d0f50acaa04)
![a140b90d1711b7002e606cfb83dc20f0](https://github.com/user-attachments/assets/f7d549c4-4a0f-4925-b1e7-8250fe72bf06)
![5b0d940d7e6d8f4877b6ed556396ac39](https://github.com/user-attachments/assets/540de4fc-1817-43cf-a9fd-98f5e000de3c)
![QQ_1728578665297](https://github.com/user-attachments/assets/50a101d6-d498-445a-a2d1-6f479a00fd36)

### 创建实例
![QQ_1728576899530](https://github.com/user-attachments/assets/7f675e36-ceb2-455d-b6f1-9893961596db)
![QQ_1728576938346](https://github.com/user-attachments/assets/6120d0f9-b8c3-4bd6-a763-284d182c8d40)

### 暗黑模式
![QQ_1728578763382](https://github.com/user-attachments/assets/ff7175ce-b085-4b7b-aaea-264d4782e916)

**Comment by mayooot** [comment]
good job！

**Comment by Harry-zklcdc** [comment]
已整理完毕，开源地址：[XShengTech/gpu-docker-api](https://github.com/XShengTech/gpu-docker-api)

前后端：[XShengTech/MEGREZ](https://github.com/XShengTech/MEGREZ)
