### ISSUE TITLE
缺少文件./etc/config.toml

### ISSUE THREAD

**Issue by iomgaa** [mayooot/gpu-docker-api#3]
## 环境
ubuntu 22.04
release 0.0.1（非自己编译）

## 错误信息
sudo ./gpu-docker-api-linux-amd64
GPU-DOCKER-API
 BRANCH: main
 Version: 0.0.1
 COMMIT: 24b2735f2154c40c40a39487e90cda2b5947e33a
 GoVersion: go1.21.4
 BuildTime: 2024-01-01T20:12:26+0800

2024/01/12 09:44:40 main.go:46: [fatal] open ./etc/config.toml: no such file or directory

**Comment by mayooot** [comment]
在 `gpu-docker-api-linux-amd64` 目录下，添加 `etc/config.toml`，详情见：https://github.com/mayooot/gpu-docker-api/blob/main/etc/config.toml
