### ISSUE TITLE
10.10.10.21:2376无法访问

### ISSUE THREAD

**Issue by iomgaa** [mayooot/gpu-docker-api#4]
## 环境
ubuntu 22.04
release 0.0.1（非自己编译）

## 错误信息
sudo ./gpu-docker-api-linux-amd64
GPU-DOCKER-API
 BRANCH: main
 Version: 0.0.1
 COMMIT: 24b2735f2154c40c40a39487e90cda2b5947e33a
 GoVersion: go1.21.4
 BuildTime: 2024-01-01T20:12:26+0800

2024/01/12 10:03:50 main.go:46: [fatal] Get "http://10.10.10.21:2376/api/v1/detect/gpu": dial tcp 10.10.10.21:2376: i/o timeout

**Comment by mayooot** [comment]
> ## 环境
> ubuntu 22.04 release 0.0.1（非自己编译）
> 
> ## 错误信息
> sudo ./gpu-docker-api-linux-amd64 GPU-DOCKER-API BRANCH: main Version: 0.0.1 COMMIT: [24b2735](https://github.com/mayooot/gpu-docker-api/commit/24b2735f2154c40c40a39487e90cda2b5947e33a) GoVersion: go1.21.4 BuildTime: 2024-01-01T20:12:26+0800
> 
> 2024/01/12 10:03:50 main.go:46: [fatal] Get "http://10.10.10.21:2376/api/v1/detect/gpu": dial tcp 10.10.10.21:2376: i/o timeout

你是否下载并运行了 [detect-gpu](https://github.com/mayooot/detect-gpu)？请看 [README](https://github.com/mayooot/gpu-docker-api/blob/main/README.md#modify-configuration-file-optional) 中的这个章节，你需要修改地址为你运行 `detect-gpu` 的地址。

**Comment by iomgaa** [comment]
非常感谢您的指点，我修正了ip地址后问题解决了。但是我现在不知道该如何进入控制台了？直接使用ip:2378会显示404。
./gpu-docker-api-linux-amd64
GPU-DOCKER-API
 BRANCH: main
 Version: 0.0.1-8-g2812a36
 COMMIT: 2812a36a0861cf73ea3b6ceca038263c944b2758
 GoVersion: go1.21.6
 BuildTime: 2024-01-12T10:11:55+0800

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.(*program).Start.func1 (1 handlers)
[GIN-debug] POST   /api/v1/containers        --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).run-fm (1 handlers)
[GIN-debug] DELETE /api/v1/containers/:name  --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).delete-fm (1 handlers)
[GIN-debug] POST   /api/v1/containers/:name/execute --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).execute-fm (1 handlers)
[GIN-debug] PATCH  /api/v1/containers/:name/gpu --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).patchGpuInfo-fm (1 handlers)
[GIN-debug] PATCH  /api/v1/containers/:name/volume --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).pathVolumeInfo-fm (1 handlers)
[GIN-debug] PATCH  /api/v1/containers/:name/stop --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).stop-fm (1 handlers)
[GIN-debug] PATCH  /api/v1/containers/:name/restart --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).restart-fm (1 handlers)
[GIN-debug] POST   /api/v1/containers/:name/commit --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).commit-fm (1 handlers)
[GIN-debug] GET    /api/v1/containers/:name  --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).info-fm (1 handlers)
[GIN-debug] POST   /api/v1/volumes           --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).create-fm (1 handlers)
[GIN-debug] DELETE /api/v1/volumes/:name     --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).delete-fm (1 handlers)
[GIN-debug] PATCH  /api/v1/volumes/:name/size --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).patchSize-fm (1 handlers)
[GIN-debug] GET    /api/v1/volumes/:name     --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).info-fm (1 handlers)
[GIN-debug] GET    /api/v1/resources/gpus    --> github.com/mayooot/gpu-docker-api/internal/api.(*Resource).getGpus-fm (1 handlers)
[GIN-debug] GET    /api/v1/resources/ports   --> github.com/mayooot/gpu-docker-api/internal/api.(*Resource).getUsedPorts-fm (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :2378

**Comment by mayooot** [comment]
> 非常感谢您的指点，我修正了ip地址后问题解决了。但是我现在不知道该如何进入控制台了？直接使用ip:2378会显示404。 ./gpu-docker-api-linux-amd64 GPU-DOCKER-API BRANCH: main Version: 0.0.1-8-g2812a36 COMMIT: [2812a36](https://github.com/mayooot/gpu-docker-api/commit/2812a36a0861cf73ea3b6ceca038263c944b2758) GoVersion: go1.21.6 BuildTime: 2024-01-12T10:11:55+0800
> 
> [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
> 
> * using env:	export GIN_MODE=release
> * using code:	gin.SetMode(gin.ReleaseMode)
> 
> [GIN-debug] GET /ping --> main.(*program).Start.func1 (1 handlers) [GIN-debug] POST /api/v1/containers --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).run-fm (1 handlers) [GIN-debug] DELETE /api/v1/containers/:name --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).delete-fm (1 handlers) [GIN-debug] POST /api/v1/containers/:name/execute --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).execute-fm (1 handlers) [GIN-debug] PATCH /api/v1/containers/:name/gpu --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).patchGpuInfo-fm (1 handlers) [GIN-debug] PATCH /api/v1/containers/:name/volume --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).pathVolumeInfo-fm (1 handlers) [GIN-debug] PATCH /api/v1/containers/:name/stop --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).stop-fm (1 handlers) [GIN-debug] PATCH /api/v1/containers/:name/restart --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).restart-fm (1 handlers) [GIN-debug] POST /api/v1/containers/:name/commit --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).commit-fm (1 handlers) [GIN-debug] GET /api/v1/containers/:name --> github.com/mayooot/gpu-docker-api/internal/api.(*ContainerHandler).info-fm (1 handlers) [GIN-debug] POST /api/v1/volumes --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).create-fm (1 handlers) [GIN-debug] DELETE /api/v1/volumes/:name --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).delete-fm (1 handlers) [GIN-debug] PATCH /api/v1/volumes/:name/size --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).patchSize-fm (1 handlers) [GIN-debug] GET /api/v1/volumes/:name --> github.com/mayooot/gpu-docker-api/internal/api.(*VolumeHandler).info-fm (1 handlers) [GIN-debug] GET /api/v1/resources/gpus --> github.com/mayooot/gpu-docker-api/internal/api.(*Resource).getGpus-fm (1 handlers) [GIN-debug] GET /api/v1/resources/ports --> github.com/mayooot/gpu-docker-api/internal/api.(*Resource).getUsedPorts-fm (1 handlers) [GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value. Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details. [GIN-debug] Listening and serving HTTP on :2378

实际上它并没有控制台，或者说 web 端。你可以使用 Postman/Apifox 导入 [json](https://github.com/mayooot/gpu-docker-api/blob/main/api/gpu-docker-api.openapi.json)就可以看到详细的使用教程了。

另外你可以进去群聊。
![IMG_0279](https://github.com/mayooot/gpu-docker-api/assets/85121496/95c7ecb2-8b9b-4028-aa00-3100a095e7ef)
